# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20170802_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resulttag', to='main_page.Tags'),
        ),
    ]
