# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20170805_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main_page.Tags'),
        ),
    ]
