# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20170806_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Tags'),
        ),
    ]
